---
- name: Add apt key
  apt_key:
   url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
   state: present

- name: Run command
  command:
    cmd: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: update
  apt:
   update_cache: yes

- name: install jenkins
  apt:
   name: "{{jenkins}}"
   state: present