---
- name: install the webserver and java using import and include tasks
  hosts: webservers
  gather_facts: true
  become: yes
  tasks:
  - include_tasks: install_webserver_{{ansible_os_family}}.yml
  - include_tasks: install_java_{{ansible_os_family}}.yml
  - include_tasks: create_file_{{ansible_os_family}}.yml