---
- name: Download the tomcat
  get_url:
   url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.47/bin/apache-tomcat-8.5.47.tar.gz
   dest: /home/ansible/apache-tomcat-8.5.47.tar.gz
   force_basic_auth: yes
