---
- name: copy the context.xml to manager
  template:
   src: context.xml.j2
   dest: /opt/tomcat/webapps/manager/META-INF/context.xml
  notify: restart tomcat 



- name: copy the context.xml to host manager
  template:
   src: context.xml.j2
   dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
  notify: restart tomcat   